
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: web-1_development

test:
  <<: *default
  database: web-1_test

production:
  <<: *default
  database: web-1_production
  username: web-1
  password: <%= ENV['WEB-1_DATABASE_PASSWORD'] %>
